package domain.trader

import application.signal.SignalGenerator
import domain.algorithm.TradingAlgorithm
import domain.assets.Quote
import domain.assets.security.SecurityHolding
import domain.assets.security.SecurityIdentifier
import domain.signal.TradingSignal
import java.util.UUID

//===========================================================//
/**
 * Represents a virtual trader that is responsible for one security
 *
 * The trader owns allocated capital, current holding batches and activate
 * trading algorithm that is (will be) decided by the Algorithm Manager.
 * It only created trading signals based on given quote
 *
 * @param id the unique trader id
 * @param stockName the display name of the stock handled by the trader
 * @param securityIdentifier identifier of the traded security
 * @param m_AllocatedCapital the capital currently allocated by the trader
 * @param m_Holdings holding batches of this security
 * @param m_Algorithm currently used trading algorithm
 */
// ===========================================================//

class Trader(
    val id: UUID,
    val stockName: String,
    val securityIdentifier: SecurityIdentifier,
    private var m_AllocatedCapital: Double,
    private var m_Holdings: MutableList<SecurityHolding>,
    private var m_Algorithm: TradingAlgorithm,
    private var m_SignalGenerator: SignalGenerator = SignalGenerator()
) {
    init {
        require(!stockName.isBlank()) {"StockName"}
        require(m_AllocatedCapital >= 0.0) {"AllocatedCapital"}
    }

    //===========================================================//
    //===========================================================//
    // Public Method(es)


    fun createSignals(quote: Quote): List<TradingSignal>{
        val currentPrice = quote.currentPrice

        val output = m_Algorithm.run(
            m_Holdings,
            m_AllocatedCapital,
            currentPrice,
        )

        var stockCount = getCurrentStockCount()

        if(output.buy != null) stockCount += output.buy.amount

        if(output.sell != null) stockCount -= getSellAmount(output.sell)

        return m_SignalGenerator.createSignal(
            output,
            m_AllocatedCapital,
            currentPrice,
            stockCount
        )
    }
    //===========================================================//
    /**
     * Applies a successfully executed buy order to this trader.
     *
     * This method should only be called after the trading service has confirmed
     * that the buy order was executed successfully.
     *
     * It decreases the allocated capital by the total buy cost and
     * adds new holding batch
     *
     * @param amount the number of buy shares
     * @param entryPrice the price which the shares were bought
     */
    //===========================================================//
    fun applyExecutedBuy(amount: Long, entryPrice: Double){
        require(amount > 0L) { "Amount"}
        require(entryPrice >= 0.0) {"EntryPrice"}

        val cost = amount * entryPrice

        require(cost <= m_AllocatedCapital){
            "Not enough capital"
        }

        m_AllocatedCapital -= cost
        m_Holdings.add(
            SecurityHolding(
                entryPrice,
                amount,
            )
        )
    }
    //===========================================================//
    /**
     * Applies a successfully executed sell order to this trader.
     *
     * This method should only be called after the trading service has confirmed
     * that the sell order was executed successfully.
     *
     * @param sell the sell output generated by the algorithm
     * @param entryPrice the price which the shares were sold
     */
    //===========================================================//
    fun applyExecutionSell(sell: TradingAlgorithm.Output.Sell, entryPrice: Double){
        require(entryPrice >= 0.0) {"EntryPrice"}

        sell.batches.forEach{ batch ->
            val holding = batch.first
            val amountToSell = batch.second

            require(amountToSell > 0L) {"SellAmount"}
            require(amountToSell <= holding.amount) {"SellAmount"}
            require(m_Holdings.contains(holding)) {"Holding"}

            m_Holdings.remove(holding)

            if(amountToSell != holding.amount){
                m_Holdings.add(
                    SecurityHolding(
                        holding.entryPrice,
                        holding.amount - amountToSell,
                    )
                )
            }

            m_AllocatedCapital += amountToSell * entryPrice
        }
    }

    //===========================================================//

    fun getCurrentStockCount(): Long {
        var ret = 0L
        m_Holdings.forEach { ret += it.amount }
        return ret
    }

    //===========================================================//
    /**
     * This method should be called by the Algorithm Manager.
     * @param newAlgorithm algorithm that manager decided would be best
     */
    fun setAlgorithm(newAlgorithm: TradingAlgorithm){
        m_Algorithm = newAlgorithm
    }

    //===========================================================//

    fun getAllocatedCapital(): Double {
        return m_AllocatedCapital
    }

    //===========================================================//

    fun getHoldings(): List<SecurityHolding> {
        return m_Holdings.toList()
    }

    //===========================================================//
    //===========================================================//
    // Private Method(es)

    private fun getSellAmount(sell: TradingAlgorithm.Output.Sell): Long {
        var ret = 0L
        sell.batches.forEach{ ret += it.second }
        return ret
    }
}