spring:

  config:
    import: "file:./.env[.properties]"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/trading

  ibkr:
    host: ${IBKR_HOST}
    port: ${IBKR_PORT}
    client-id: ${IBKR_CLIENT_ID}

  flyway:
    locations: classpath:database/migration

  datasource:
    url: jdbc:postgresql://${TRADING_DB_URL}/${TRADING_DB_NAME}
    username: ${TRADING_DB_USERNAME}
    password: ${TRADING_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false


logging:
  config: classpath:logback.xml
  level:
    root: INFO


server:
  port: 8080